workflows:
  android-workflow:
    name: ⭐ عالم الأطفال - Test Build

    environment:
      flutter: stable

    scripts:

      - name: Clean project
        script: |
          flutter clean

      - name: Get packages
        script: |
          flutter pub get

      - name: Generate App Icon
        script: |
          dart run flutter_launcher_icons

      - name: Build Debug APK Split
        script: |
          flutter build apk --debug --split-per-abi

    artifacts:
      - build/app/outputs/flutter-apk/*.apk